[2024-10-31T01:20:55.908-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-31T01:20:55.964-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.extract_data manual__2024-10-29T17:19:02.985662+00:00 [queued]>
[2024-10-31T01:20:56.004-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.extract_data manual__2024-10-29T17:19:02.985662+00:00 [queued]>
[2024-10-31T01:20:56.006-0300] {taskinstance.py:2865} INFO - Starting attempt 5 of 5
[2024-10-31T01:20:56.089-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract_data> on 2024-10-29 17:19:02.985662+00:00
[2024-10-31T01:20:56.112-0300] {standard_task_runner.py:72} INFO - Started process 121730 to run task
[2024-10-31T01:20:56.135-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_redshift_dag_variables_bcra', 'extract_data', 'manual__2024-10-29T17:19:02.985662+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/dag_variables_bcra.py', '--cfg-path', '/tmp/tmpqob16grw']
[2024-10-31T01:20:56.177-0300] {standard_task_runner.py:105} INFO - Job 286: Subtask extract_data
[2024-10-31T01:20:58.027-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_redshift_dag_variables_bcra.extract_data manual__2024-10-29T17:19:02.985662+00:00 [running]> on host DESKTOP-MVFODGC.
[2024-10-31T01:20:58.256-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_redshift_dag_variables_bcra' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T17:19:02.985662+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T17:19:02.985662+00:00'
[2024-10-31T01:20:58.265-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-31T01:20:58.269-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-31T01:20:58.274-0300] {logging_mixin.py:190} INFO - Current task name:extract_data state:running start_date:2024-10-31 04:20:55.967156+00:00
[2024-10-31T01:20:58.278-0300] {logging_mixin.py:190} INFO - Dag name:etl_redshift_dag_variables_bcra and current dag run status:running
[2024-10-31T01:20:58.284-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-31T01:20:58.574-0300] {logging_mixin.py:190} WARNING - /home/nico/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1099 InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.bcra.gob.ar'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2024-10-31T01:20:58.613-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/dag_variables_bcra.py", line 45, in extract_task_callable
    df = extract_data(execution_date, variables_ids)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/extract_data.py", line 31, in extract_data
    raise Exception(f"Error en la solicitud a la API. Código error: {response.status_code}")
Exception: Error en la solicitud a la API. Código error: 404
[2024-10-31T01:20:58.666-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-31T01:20:58.677-0300] {logging_mixin.py:190} INFO - Task start:2024-10-31 04:20:55.967156+00:00 end:2024-10-31 04:20:58.665152+00:00 duration:2.697996
[2024-10-31T01:20:58.684-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_data> dag:<DAG: etl_redshift_dag_variables_bcra> dagrun:<DagRun etl_redshift_dag_variables_bcra @ 2024-10-29 17:19:02.985662+00:00: manual__2024-10-29T17:19:02.985662+00:00, state:running, queued_at: 2024-10-31 04:08:19.582555+00:00. externally triggered: True>
[2024-10-31T01:20:58.689-0300] {logging_mixin.py:190} INFO - Failure caused by Error en la solicitud a la API. Código error: 404
[2024-10-31T01:20:58.694-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_redshift_dag_variables_bcra, task_id=extract_data, run_id=manual__2024-10-29T17:19:02.985662+00:00, execution_date=20241029T171902, start_date=20241031T042055, end_date=20241031T042058
[2024-10-31T01:20:58.893-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-31T01:20:58.898-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 286 for task extract_data (Error en la solicitud a la API. Código error: 404; 121730)
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/dag_variables_bcra.py", line 45, in extract_task_callable
    df = extract_data(execution_date, variables_ids)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/extract_data.py", line 31, in extract_data
    raise Exception(f"Error en la solicitud a la API. Código error: {response.status_code}")
Exception: Error en la solicitud a la API. Código error: 404
[2024-10-31T01:20:58.959-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-31T01:20:59.363-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-31T01:20:59.552-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
