[2024-10-20T11:40:27.574-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-20T11:40:27.625-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.transform_data manual__2024-10-20T14:35:05.990378+00:00 [queued]>
[2024-10-20T11:40:27.667-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.transform_data manual__2024-10-20T14:35:05.990378+00:00 [queued]>
[2024-10-20T11:40:27.672-0300] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-20T11:40:27.760-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): transform_data> on 2024-10-20 14:35:05.990378+00:00
[2024-10-20T11:40:27.788-0300] {standard_task_runner.py:72} INFO - Started process 106266 to run task
[2024-10-20T11:40:27.798-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_redshift_dag_variables_bcra', 'transform_data', 'manual__2024-10-20T14:35:05.990378+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/dag_variables_bcra.py', '--cfg-path', '/tmp/tmpyqffqfvm']
[2024-10-20T11:40:27.809-0300] {standard_task_runner.py:105} INFO - Job 66: Subtask transform_data
[2024-10-20T11:40:28.001-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_redshift_dag_variables_bcra.transform_data manual__2024-10-20T14:35:05.990378+00:00 [running]> on host DESKTOP-MVFODGC.
[2024-10-20T11:40:28.298-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_redshift_dag_variables_bcra' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T14:35:05.990378+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-20T14:35:05.990378+00:00'
[2024-10-20T11:40:28.306-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-20T11:40:28.309-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-20T11:40:28.316-0300] {logging_mixin.py:190} INFO - Current task name:transform_data state:running start_date:2024-10-20 14:40:27.629815+00:00
[2024-10-20T11:40:28.321-0300] {logging_mixin.py:190} INFO - Dag name:etl_redshift_dag_variables_bcra and current dag run status:running
[2024-10-20T11:40:28.326-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-20T11:40:28.332-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: transform_data() missing 2 required positional arguments: 'input_parquet' and 'output_csv'
[2024-10-20T11:40:28.370-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-20T11:40:28.373-0300] {logging_mixin.py:190} INFO - Task start:2024-10-20 14:40:27.629815+00:00 end:2024-10-20 14:40:28.368802+00:00 duration:0.738987
[2024-10-20T11:40:28.387-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_data> dag:<DAG: etl_redshift_dag_variables_bcra> dagrun:<DagRun etl_redshift_dag_variables_bcra @ 2024-10-20 14:35:05.990378+00:00: manual__2024-10-20T14:35:05.990378+00:00, state:running, queued_at: 2024-10-20 14:35:06.216665+00:00. externally triggered: True>
[2024-10-20T11:40:28.392-0300] {logging_mixin.py:190} INFO - Failure caused by transform_data() missing 2 required positional arguments: 'input_parquet' and 'output_csv'
[2024-10-20T11:40:28.398-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_redshift_dag_variables_bcra, task_id=transform_data, run_id=manual__2024-10-20T14:35:05.990378+00:00, execution_date=20241020T143505, start_date=20241020T144027, end_date=20241020T144028
[2024-10-20T11:40:28.504-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-20T11:40:28.507-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 66 for task transform_data (transform_data() missing 2 required positional arguments: 'input_parquet' and 'output_csv'; 106266)
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
TypeError: transform_data() missing 2 required positional arguments: 'input_parquet' and 'output_csv'
[2024-10-20T11:40:28.555-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-20T11:40:28.941-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-20T11:40:29.047-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
