[2024-10-30T20:27:52.723-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T20:27:52.901-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.load_data scheduled__2024-10-23T00:01:00+00:00 [queued]>
[2024-10-30T20:27:53.026-0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_redshift_dag_variables_bcra.load_data scheduled__2024-10-23T00:01:00+00:00 [queued]>
[2024-10-30T20:27:53.029-0300] {taskinstance.py:2865} INFO - Starting attempt 5 of 5
[2024-10-30T20:27:53.290-0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data> on 2024-10-23 00:01:00+00:00
[2024-10-30T20:27:53.314-0300] {standard_task_runner.py:72} INFO - Started process 90485 to run task
[2024-10-30T20:27:53.333-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_redshift_dag_variables_bcra', 'load_data', 'scheduled__2024-10-23T00:01:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/dag_variables_bcra.py', '--cfg-path', '/tmp/tmptfcp2tcd']
[2024-10-30T20:27:53.346-0300] {standard_task_runner.py:105} INFO - Job 202: Subtask load_data
[2024-10-30T20:27:53.946-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_redshift_dag_variables_bcra.load_data scheduled__2024-10-23T00:01:00+00:00 [running]> on host DESKTOP-MVFODGC.
[2024-10-30T20:27:54.963-0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_redshift_dag_variables_bcra' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T00:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-23T00:01:00+00:00'
[2024-10-30T20:27:54.968-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-30T20:27:54.974-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-30T20:27:54.977-0300] {logging_mixin.py:190} INFO - Current task name:load_data state:running start_date:2024-10-30 23:27:52.908425+00:00
[2024-10-30T20:27:54.983-0300] {logging_mixin.py:190} INFO - Dag name:etl_redshift_dag_variables_bcra and current dag run status:running
[2024-10-30T20:27:54.989-0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T20:27:58.439-0300] {_write.py:249} ERROR - identifier must contain only alphanumeric characters, spaces, underscores, or hyphens
[2024-10-30T20:27:58.447-0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/load_to_redshift.py", line 41, in load_to_redshift
    wr.redshift.to_sql(
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_utils.py", line 126, in inner
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_config.py", line 715, in wrapper
    return function(**args)
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_write.py", line 200, in to_sql
    created_table, created_schema = _create_table(
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_utils.py", line 397, in _create_table
    f"CREATE TABLE IF NOT EXISTS {_identifier(schema)}.{_identifier(table)} (\n"
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_utils.py", line 33, in _identifier
    return _sql_utils.identifier(sql, sql_mode="ansi")
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_sql_utils.py", line 30, in identifier
    raise exceptions.InvalidArgumentValue(
awswrangler.exceptions.InvalidArgumentValue: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/dag_variables_bcra.py", line 61, in load_task_callable
    load_to_redshift(df_transformado, conn_params)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/load_to_redshift.py", line 55, in load_to_redshift
    raise Exception(f"Error en la conexi贸n o carga de datos a Redshift: {e}")
Exception: Error en la conexi贸n o carga de datos a Redshift: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens
[2024-10-30T20:27:58.695-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-30T20:27:58.701-0300] {logging_mixin.py:190} INFO - Task start:2024-10-30 23:27:52.908425+00:00 end:2024-10-30 23:27:58.694142+00:00 duration:5.785717
[2024-10-30T20:27:58.707-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_data> dag:<DAG: etl_redshift_dag_variables_bcra> dagrun:<DagRun etl_redshift_dag_variables_bcra @ 2024-10-23 00:01:00+00:00: scheduled__2024-10-23T00:01:00+00:00, state:running, queued_at: 2024-10-30 23:10:17.652941+00:00. externally triggered: False>
[2024-10-30T20:27:58.712-0300] {logging_mixin.py:190} INFO - Failure caused by Error en la conexi贸n o carga de datos a Redshift: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens
[2024-10-30T20:27:58.715-0300] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_redshift_dag_variables_bcra, task_id=load_data, run_id=scheduled__2024-10-23T00:01:00+00:00, execution_date=20241023T000100, start_date=20241030T232752, end_date=20241030T232758
[2024-10-30T20:27:58.980-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T20:27:58.983-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 202 for task load_data (Error en la conexi贸n o carga de datos a Redshift: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens; 90485)
Traceback (most recent call last):
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/load_to_redshift.py", line 41, in load_to_redshift
    wr.redshift.to_sql(
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_utils.py", line 126, in inner
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_config.py", line 715, in wrapper
    return function(**args)
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_write.py", line 200, in to_sql
    created_table, created_schema = _create_table(
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_utils.py", line 397, in _create_table
    f"CREATE TABLE IF NOT EXISTS {_identifier(schema)}.{_identifier(table)} (\n"
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/redshift/_utils.py", line 33, in _identifier
    return _sql_utils.identifier(sql, sql_mode="ansi")
  File "/home/nico/.local/lib/python3.10/site-packages/awswrangler/_sql_utils.py", line 30, in identifier
    raise exceptions.InvalidArgumentValue(
awswrangler.exceptions.InvalidArgumentValue: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/nico/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/dag_variables_bcra.py", line 61, in load_task_callable
    load_to_redshift(df_transformado, conn_params)
  File "/mnt/c/Users/Nicolas/OneDrive - BCRA/Cursos/Python Data Application (ITBA)/variables-economicas/dags/../scripts/load_to_redshift.py", line 55, in load_to_redshift
    raise Exception(f"Error en la conexi贸n o carga de datos a Redshift: {e}")
Exception: Error en la conexi贸n o carga de datos a Redshift: identifier must contain only alphanumeric characters, spaces, underscores, or hyphens
[2024-10-30T20:27:59.067-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-30T20:27:59.204-0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T20:27:59.224-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
